services:
  client:
    build:
      context: ./apps/client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - app-network
    environment:
      - VITE_API_URL=http://api:8080
    depends_on:
      - api

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    networks:
      - app-network

  file-upload:
    build:
      context: ./apps/file-upload
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
