# fly.toml app configuration file generated for immudb-vault-client on 2024-07-23T17:40:23+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'immudb-vault-client'
primary_region = 'waw'

[build]

[http_service]
  internal_port = 5173
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
